apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginx:1.25
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-hpa-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/orenhandel/argo.git   # 🔄 replace with your repo if you want GitOps
    path: manifests
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  # no syncPolicy specified -> defaults (manual sync, no extra options)
