apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-java
  namespace: java-tests
  labels:
    app: basic-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-java
  template:
    metadata:
      labels:
        app: basic-java
    spec:
      containers:
      - name: java-app
        image: eclipse-temurin:17-jdk
        command: ["/bin/bash", "-c"]
        args:
          - |
            cat > BasicJavaApp.java << 'EOF'
            import java.util.ArrayList;
            import java.util.List;
            import java.util.Random;
            public class BasicJavaApp {
                public static void main(String[] args) throws Exception {
                    List<byte[]> memory = new ArrayList<>();
                    Random rand = new Random();
                    System.out.println("Basic Java Application started");
                    System.out.println("Java Version: " + System.getProperty("java.version"));
                    System.out.println("Max Memory: " + Runtime.getRuntime().maxMemory() / (1024*1024) + "MB");
                    
                    int iteration = 0;
                    while (true) {
                        iteration++;
                        // Allocate memory
                        memory.add(new byte[1024 * 1024]); // 1MB
                        if (memory.size() > 100) {
                            memory.remove(0); // Keep around 100MB
                        }
                        
                        // Perform CPU intensive work
                        double result = 0;
                        for (int i = 0; i < 1000000; i++) {
                            result += Math.sqrt(rand.nextDouble()) * Math.sin(i);
                        }
                        
                        Thread.sleep(3000);
                        
                        if (iteration % 10 == 0) {
                            long usedMemory = (Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory()) / (1024*1024);
                            System.out.println("Iteration: " + iteration + 
                                             ", List size: " + memory.size() + "MB" +
                                             ", Used memory: " + usedMemory + "MB" +
                                             ", CPU work result: " + String.format("%.2f", result));
                        }
                    }
                }
            }
            EOF
            javac BasicJavaApp.java
            java -Xms128m -Xmx512m -XX:+UseG1GC -XX:+PrintGCDetails BasicJavaApp
        env:
        - name: JAVA_TOOL_OPTIONS
          value: -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:G1HeapRegionSize=2m -XX:InitiatingHeapOccupancyPercent=45
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "768Mi"

